### ISSUE TITLE
server error 500

### ISSUE THREAD

**Issue by sahilshukla3003** [Hitstar53/AI-product-reviewer#45]
hey , I am unable to access reviews , i have tried using product name and product link both but still getting same error .....
![Screenshot from 2024-03-04 12-07-08](https://github.com/Hitstar53/AI-product-reviewer/assets/124785012/8e14a66c-982d-4e7f-8716-0e9a1faf05ff)

**Comment by Hitstar53** [comment]
I dont know what the issue might be, i have not maintained the repository to latest updated packages, howvever you can try cloning the backend branch, it has some difference, the main branch was for a lighter dployable version
